baseURL: 'https://j178.dev/'
languageCode: zh-cn
title: J178's Blog
theme: PaperMod
enableInlineShortcodes: true
enableGitInfo: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

params:
  comments: true
  ShowShareButtons: false
  ShowReadingTime: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  TocOpen: true
  homeInfoParams:
    Title: J178 的博客
    Content: |
      你好，我是 J178，一名普通的程序员，喜欢研究各种乱七八糟的东西，偶尔会在这里记录一下，谢谢~
  socialIcons:
    - name: github
      url: https://github.com/j178
    - name: email
      url : mailto:i@j178.dev
    - name: twitter
      url: 'https://twitter.com/niceoe'
    - name: Rss
      url: index.xml
  editPost:
    URL: 'https://github.com/j178/blog/issues/new?title=Suggest%20Changes:%20'
    Text: "Suggest Changes"
    appendFilePath: true
menu:
  main:
    - name: Archive
      url: /archives/
      weight: 5
    - name: Search
      url: /search/
      weight: 10
    - name: Tags
      url: /tags/
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  goldmark:
    renderer:
      unsafe: true
