baseURL: 'https://j178.dev/'
languageCode: zh-cn
title: J178's Blog
theme: PaperMod
enableInlineShortcodes: true
enableGitInfo: true
enableRobotsTXT: true
enableEmoji: true
frontmatter:
  date: [':default']
permalinks:
  posts: /:slug/

params:
  comments: true
  ShowShareButtons: false
  ShowReadingTime: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  TocOpen: true
  socialIcons:
    - name: github
      url: https://github.com/j178
    - name: email
      url : mailto:i@j178.dev
    - name: twitter
      url: 'https://twitter.com/niceoe'
    - name: Rss
      url: index.xml
  editPost:
    URL: 'https://github.com/j178/blog/edit/master/content'
    Text: "Suggest Changes"
    appendFilePath: true
menu:
  main:
    - name: Archive
      url: /archives/
      weight: 5
    - name: Search
      url: /search/
      weight: 10
    - name: Tags
      url: /tags/
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  highlight:
    # use CSS class, not inline CSS styles. 
    noClasses: false
    codeFences: true
  goldmark:
    renderer:
      unsafe: true
