# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link:  阅读全文
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
  # - tag
- tagcloud
- archive
- links

# Links
links:
  GitHub: https://github.com/j178

# Miscellaneous
google_analytics: "UA-91646414-1"
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
# duoshuo_shortname: reqianduan

# Baidu share
# baidushare: true